language: node_js

node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo generate

deploy:
  local-dir: public
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
