version: 2.0.11
url: https://qutang.github.io/cutie/
logo: #
slogan: Infinite possibilities-

announcement:
  text: 'New theme initialized : hexo-theme-cutie :3'

global:
  comment_system: livere
  scheme: 
    name: Taurus
    color: flower
  icon_set: blue-shadow
  use_animation: true

page_404:
  tencent_404: false

menu:
  Resume: 
    link: #
  "Menu item":
    link: #

post:
  allow_share: true
  allow_modification: false
  allow_commercial: false
  use_lightgallery: true
  allow_comment: false
  toc_level: 2
  enable_unread_badge: false

livere:
  id: 'city'
  uid:

social:
  github: https://github.com/leewp14  
